### ISSUE TITLE
Режим забора воздуха 2

### ISSUE THREAD

**Issue by Daemon256** [airens/tion_home_assistant#19]
Так и не работает. Выдаёт ошибку. Рано закрыли Issues :)

`# Управляем тион когда уже все проснулись
- alias: control_breezer_day_10
  trigger:
    platform: time
    at: "10:00:00"

  condition:
      condition: state # если свет включен
      entity_id: switch.osveshchenie_ulitsy_21
      state: 'on' 
  action:
  - service: climate.set_fan_mode
    entity_id: climate.tion_breezer_3s_1
    data:
      fan_mode: 1:0
  - service: climate.set_hvac_mode
    entity_id: climate.tion_breezer_3s_1
    data:
      hvac_mode: fan_only
      `

`Traceback (most recent call last):
File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1152, in _sendfile_fallback
read = await self.run_in_executor(None, file.readinto, view)
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 485, in start
resp, reset = await task
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 440, in _handle_request
reset = await self.finish_response(request, resp, start_time)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 591, in finish_response
await prepare_meth(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_fileresponse.py", line 241, in prepare
return await self._sendfile(request, fobj, offset, count)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_fileresponse.py", line 96, in _sendfile
await loop.sendfile(transport, fobj, offset, count)
File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1131, in sendfile
return await self._sendfile_fallback(transport, file,
File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1161, in _sendfile_fallback
await proto.restore()
File "/usr/local/lib/python3.8/asyncio/base_events.py", line 263, in restore
self._transport.resume_reading()
File "/usr/local/lib/python3.8/asyncio/sslproto.py", line 344, in resume_reading
self._ssl_protocol._transport.resume_reading()
AttributeError: 'NoneType' object has no attribute 'resume_reading'
2021-03-06 15:19:04 ERROR (SyncWorker_2) [tion] TionApi parameters set bad_request: speed should be in range [1; 6]`

Версия последняя 8dd2b0d

**Comment by airens** [comment]
Попробуйте 1:0 взять в кавычки

**Comment by Daemon256** [comment]
Действительно помогло.
Так же обнаружил, что перепутаны режимы:  0 - из дома; 2- с улицы
