### ISSUE TITLE
Периодически ошибки в логе

### ISSUE THREAD

**Issue by dima11235** [airens/tion_home_assistant#9]
Добрый день. Периодически, в лог валятся следующие ошибки:

2020-08-31 15:50:56 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 583, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 268, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 299, in _async_write_ha_state
    attr = self.capability_attributes
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 204, in capability_attributes
    data[ATTR_FAN_MODES] = self.fan_modes
  File "/config/custom_components/tion/climate.py", line 109, in fan_modes
    _fan_modes.extend(range(0, int(self._breezer.speed_limit) + 1))
ValueError: invalid literal for int() with base 10: 'NaN'
2020-08-31 15:51:56 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 583, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 268, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 299, in _async_write_ha_state
    attr = self.capability_attributes
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 204, in capability_attributes
    data[ATTR_FAN_MODES] = self.fan_modes
  File "/config/custom_components/tion/climate.py", line 109, in fan_modes
    _fan_modes.extend(range(0, int(self._breezer.speed_limit) + 1))
ValueError: invalid literal for int() with base 10: 'NaN'

**Comment by airens** [comment]
Здравствуйте, по какой-то причине сервера Tion не дают максимальную скорость для вашего бризера, вставил заглушку, чтобы это безопасно обрабатывалось и скорости выставлялись на 0-6, проверьте
